[project]
name = "orbitit"
version = "0.8.0"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pillow>=12.3.0",
    "pyopengl>=3.1.10",
    "ruff>=0.16.4",
    "wxPython==4.2.4",
]

[tool.uv.sources]
wxPython = [
    { url = "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04/wxpython-4.2.4-cp310-cp310-linux_x86_64.whl", marker = "python_version == '3.10' and sys_platform == 'linux' and platform_machine == 'x86_64'" },
    { url = "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04/wxpython-4.2.4-cp311-cp311-linux_x86_64.whl", marker = "python_version == '3.11' and sys_platform == 'linux' and platform_machine == 'x86_64'" },
    { url = "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04/wxpython-4.2.4-cp312-cp312-linux_x86_64.whl", marker = "python_version == '3.12' and sys_platform == 'linux' and platform_machine == 'x86_64'" },
    { url = "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04/wxpython-4.2.4-cp313-cp313-linux_x86_64.whl", marker = "python_version == '3.13' and sys_platform == 'linux' and platform_machine == 'x86_64'" },
    { url = "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04/wxpython-4.2.4-cp314-cp314-linux_x86_64.whl", marker = "python_version == '3.14' and sys_platform == 'linux' and platform_machine == 'x86_64'" },
]

[tool.uv.build-backend]
source-include = ["src/orbitit/data/**/*.off"]

[project.scripts]
orbitit = "orbitit:main"
generate_59_icosahedra = "orbitit.extra_scripts.generate_59_icosahedra:main"
generate_compound_polyhedra = "orbitit.extra_scripts.generate_compound_polyhedra:main"
generate_crosso_lattices = "orbitit.extra_scripts.generate_crosso_lattices:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ruff>=0.16.4",
]
